INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES('admin', '123456', 'duc', 'anh', '12346', 'ANH@FPT');
INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES('admin1', '123456', 'duc1', 'anh1', '12346', 'ANH@FPT');
INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES('admin2', '123456', 'duc2', 'anh2', '12346', 'ANH@FPT');
INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES('admin3', '123456', 'duc3', 'anh3', '12346', 'ANH@FPT');