INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('admin', '123456', 'duc', 'anh');
INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('admin1', '123456', 'duc1', 'anh1');
INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('admin2', '123456', 'duc2', 'anh2');
INSERT INTO USERS(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('admin3', '123456', 'duc3', 'anh3');