DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT
ALL
ON SCHEMA public TO postgres;
GRANT ALL
ON SCHEMA public TO public;
COMMENT
ON SCHEMA public IS 'standard public schema';

-- CREATE TABLE ROLES
-- (
--     role_id     INTEGER primary key,
--     role_name   varchar(30),
--     description varchar(100)
-- );
--
-- CREATE TABLE USERS
-- (
--     USERNAME   VARCHAR(50) PRIMARY KEY,
--     PASSWORD   VARCHAR(255),
--     FIRST_NAME VARCHAR(255),
--     LAST_NAME  VARCHAR(255),
--     PHONE      VARCHAR(255),
--     EMAIL      VARCHAR(255),
--     ROLE_ID    INTEGER references ROLES (role_id)
-- );

-- CREATE TABLE EVENTS
-- (
--     EVENT_ID INTEGER NOT NULL
--         CONSTRAINT EVENT_PKEY
--             PRIMARY KEY,
--     CLOSURE_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
-- );
CREATE TABLE ROLES
(
    ROLE_ID INTEGER NOT NULL
        CONSTRAINT ROLES_PKEY
            PRIMARY KEY,
    ROLE_NAME VARCHAR(30),
    DESCRIPTION VARCHAR(100)
);

ALTER TABLE ROLES OWNER TO RUITEYGGURRIUJ;

CREATE TABLE FACULTY
(
    FACULTY_ID INTEGER NOT NULL
        CONSTRAINT FACULTY_PKEY
            PRIMARY KEY,
    FACULTY_NAME VARCHAR(30) NOT NULL
);

ALTER TABLE FACULTY OWNER TO RUITEYGGURRIUJ;

CREATE TABLE USERS
(
    USERNAME VARCHAR(50) NOT NULL
        CONSTRAINT USERS_PKEY
            PRIMARY KEY,
    PASSWORD VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PHONE VARCHAR(255),
    EMAIL VARCHAR(255),
    ROLE_ID INTEGER
        CONSTRAINT USERS_ROLE_ID_FKEY REFERENCES ROLES,
    FACULTY_ID INTEGER
        CONSTRAINT USERS_FACULTY_FACULTY_ID_FK REFERENCES FACULTY
);

ALTER TABLE USERS OWNER TO RUITEYGGURRIUJ;

CREATE TABLE DEADLINE
(
    DEADLINE_ID INTEGER NOT NULL
        CONSTRAINT DEADLINE_PKEY
            PRIMARY KEY,
    CLOSURE_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE DEADLINE OWNER TO RUITEYGGURRIUJ;

CREATE TABLE ASSIGNMENT
(
    ASSIGNMENT_ID INTEGER NOT NULL
        CONSTRAINT ASSIGNMENT_PKEY
            PRIMARY KEY,
    ASSIGNMENT_NAME VARCHAR(30) NOT NULL,
    CREATE_BY VARCHAR(6) NOT NULL,
--     CLOSURE_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    DEADLINE_ID INTEGER NOT NULL
        CONSTRAINT FK_ASSIGNMENT__DEADLINE_ID REFERENCES DEADLINE,
    FACULTY_ID INTEGER NOT NULL
        CONSTRAINT FK_ASSIGNMENT__FACULTY_ID REFERENCES FACULTY
);

ALTER TABLE ASSIGNMENT OWNER TO RUITEYGGURRIUJ;

CREATE TABLE SUBMISSION
(
    SUBMISSION_ID INTEGER NOT NULL
        CONSTRAINT SUBMISSION_PKEY
            PRIMARY KEY,
    SUBMISSION_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    STATUS INTEGER NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    ASSIGNMENT_ID INTEGER NOT NULL
        CONSTRAINT FK_SUBMISSION__ASSIGNMENT_ID REFERENCES ASSIGNMENT
);

ALTER TABLE SUBMISSION OWNER TO RUITEYGGURRIUJ;

CREATE TABLE FILE
(
    FILE_ID INTEGER NOT NULL
        CONSTRAINT FILE_PKEY
            PRIMARY KEY,
    FILE_URL VARCHAR(255) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    SUBMISSION_ID INTEGER NOT NULL
        CONSTRAINT FK_FILE__SUBMISSION_ID REFERENCES SUBMISSION
);

ALTER TABLE FILE OWNER TO RUITEYGGURRIUJ;

CREATE TABLE COMMENT
(
    COMMENT_ID INTEGER NOT NULL
        CONSTRAINT COMMENT_PKEY
            PRIMARY KEY,
    CONTENT VARCHAR(1000) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    CREATED_BY VARCHAR(30) NOT NULL,
    SUBMISSION_ID INTEGER NOT NULL
        CONSTRAINT FK_COMMENT__SUBMISSION_ID REFERENCES SUBMISSION,
    USER_NAME VARCHAR(30) NOT NULL
        CONSTRAINT FK_COMMENT__USER_NAME REFERENCES USERS
);

ALTER TABLE COMMENT OWNER TO RUITEYGGURRIUJ;


-- auto_increment